#ifndef __CHIP_ctrl_REG_H__
#define __CHIP_ctrl_REG_H__
                                   
#define EMA_CTRL_REG    0x0000
#define EMA_CTRL_REG_CODE_SRAM_RM_SHIFT        0
#define EMA_CTRL_REG_CODE_SRAM_RM_MASK         0x00000003 //RW, 2 bit
#define EMA_CTRL_REG_CODE_SRAM_RME_SHIFT       2
#define EMA_CTRL_REG_CODE_SRAM_RME_MASK        0x00000004 //RW, 1 bit
#define EMA_CTRL_REG_SRAM_RM_SHIFT             4
#define EMA_CTRL_REG_SRAM_RM_MASK              0x00000030 //RW, 2 bit
#define EMA_CTRL_REG_SRAM_RME_SHIFT            6
#define EMA_CTRL_REG_SRAM_RME_MASK             0x00000040 //RW, 1 bit
#define EMA_CTRL_REG_ITAG_RTSEL_SHIFT          8
#define EMA_CTRL_REG_ITAG_RTSEL_MASK           0x00000300 //RW, 2 bit
#define EMA_CTRL_REG_ITAG_WTSEL_SHIFT          10
#define EMA_CTRL_REG_ITAG_WTSEL_MASK           0x00000c00 //RW, 2 bit
#define EMA_CTRL_REG_ICACHE_RTSEL_SHIFT        12
#define EMA_CTRL_REG_ICACHE_RTSEL_MASK         0x00003000 //RW, 2 bit
#define EMA_CTRL_REG_ICACHE_WTSEL_SHIFT        14
#define EMA_CTRL_REG_ICACHE_WTSEL_MASK         0x0000c000 //RW, 2 bit
#define EMA_CTRL_REG_DTAG_RTSEL_SHIFT          16
#define EMA_CTRL_REG_DTAG_RTSEL_MASK           0x00010000 //RW, 1 bit
#define EMA_CTRL_REG_DTAG_TURBO_SHIFT          17
#define EMA_CTRL_REG_DTAG_TURBO_MASK           0x00020000 //RW, 1 bit
#define EMA_CTRL_REG_DTAG_TSEL_SHIFT           18
#define EMA_CTRL_REG_DTAG_TSEL_MASK            0x000c0000 //RW, 2 bit
#define EMA_CTRL_REG_DCACHE_RTSEL_SHIFT        20
#define EMA_CTRL_REG_DCACHE_RTSEL_MASK         0x00300000 //RW, 2 bit
#define EMA_CTRL_REG_DCACHE_WTSEL_SHIFT        22
#define EMA_CTRL_REG_DCACHE_WTSEL_MASK         0x00c00000 //RW, 2 bit
#define EMA_CTRL_REG_DIRTY_RTSEL_SHIFT         24
#define EMA_CTRL_REG_DIRTY_RTSEL_MASK          0x01000000 //RW, 1 bit
#define EMA_CTRL_REG_DIRTY_TURBO_SHIFT         25
#define EMA_CTRL_REG_DIRTY_TURBO_MASK          0x02000000 //RW, 1 bit
#define EMA_CTRL_REG_DIRTY_WTSEL_SHIFT         26
#define EMA_CTRL_REG_DIRTY_WTSEL_MASK          0x0c000000 //RW, 2 bit
#define EMA_CTRL_REG_BUF_RTSEL_SHIFT           28
#define EMA_CTRL_REG_BUF_RTSEL_MASK            0x30000000 //RW, 2 bit
#define EMA_CTRL_REG_BUF_WTSEL_SHIFT           30
#define EMA_CTRL_REG_BUF_WTSEL_MASK            0xc0000000 //RW, 2 bit
#define EMA_CTRL2_REG   0x0004
#define EMA_CTRL2_REG_CAN_RTSEL_SHIFT          0
#define EMA_CTRL2_REG_CAN_RTSEL_MASK           0x00000003 //RW, 2 bit
#define EMA_CTRL2_REG_CAN_WTSEL_SHIFT          2
#define EMA_CTRL2_REG_CAN_WTSEL_MASK           0x0000000c //RW, 2 bit
#define EMA_CTRL2_REG_KEYEXP_RTSEL_SHIFT       4
#define EMA_CTRL2_REG_KEYEXP_RTSEL_MASK        0x00000010 //RW, 1 bit
#define EMA_CTRL2_REG_KEYEXP_TURBO_SHIFT       5
#define EMA_CTRL2_REG_KEYEXP_TURBO_MASK        0x00000020 //RW, 1 bit
#define EMA_CTRL2_REG_KEYEXP_WTSEL_SHIFT       6
#define EMA_CTRL2_REG_KEYEXP_WTSEL_MASK        0x000000c0 //RW, 2 bit
#define EMA_CTRL2_REG_ROM_RM_SHIFT             8
#define EMA_CTRL2_REG_ROM_RM_MASK              0x00000300 //RW, 2 bit
#define EMA_CTRL2_REG_ROM_RME_SHIFT            10
#define EMA_CTRL2_REG_ROM_RME_MASK             0x00000400 //RW, 1 bit
#define LOWERPOWER_REG  0x0008
#define LOWERPOWER_REG_SRAM_LS_SHIFT           0
#define LOWERPOWER_REG_SRAM_LS_MASK            0x000000ff //RW, 8 bit
#define LOWERPOWER_REG_SRAM_DS_SHIFT           8
#define LOWERPOWER_REG_SRAM_DS_MASK            0x0000ff00 //RW, 8 bit
#define LOWERPOWER_REG_SRAM_CODE_LS_SHIFT      16
#define LOWERPOWER_REG_SRAM_CODE_LS_MASK       0x00ff0000 //RW, 8 bit
#define LOWERPOWER_REG_SRAM_CODE_DS_SHIFT      24
#define LOWERPOWER_REG_SRAM_CODE_DS_MASK       0xff000000 //RW, 8 bit
#define LOWERPOWER_REG1 0x000c
#define LOWERPOWER_REG1_SRAM_PD_SHIFT          0
#define LOWERPOWER_REG1_SRAM_PD_MASK           0x000000ff //RW, 8 bit
#define LOWERPOWER_REG1_SRAM_CODE_PD_SHIFT     8
#define LOWERPOWER_REG1_SRAM_CODE_PD_MASK      0x0000ff00 //RW, 8 bit
#define LOWERPOWER_REG2 0x0010
#define LOWERPOWER_REG2_STARSE_ITAG_PD_SHIFT   0
#define LOWERPOWER_REG2_STARSE_ITAG_PD_MASK    0x00000001 //RW, 1 bit
#define LOWERPOWER_REG2_STARSE_ICACHE_PD_SHIFT 1
#define LOWERPOWER_REG2_STARSE_ICACHE_PD_MASK  0x00000002 //RW, 1 bit
#define LOWERPOWER_REG2_STARSE_DTAG_PD_SHIFT   2
#define LOWERPOWER_REG2_STARSE_DTAG_PD_MASK    0x00000004 //RW, 1 bit
#define LOWERPOWER_REG2_STARSE_DCACHE_PD_SHIFT 3
#define LOWERPOWER_REG2_STARSE_DCACHE_PD_MASK  0x00000008 //RW, 1 bit
#define LOWERPOWER_REG2_STARSE_DIRTY_PD_SHIFT  4
#define LOWERPOWER_REG2_STARSE_DIRTY_PD_MASK   0x00000010 //RW, 1 bit
#define LOWERPOWER_REG2_BUF_PD_SHIFT           5
#define LOWERPOWER_REG2_BUF_PD_MASK            0x00000020 //RW, 1 bit
#define LOWERPOWER_REG2_CAN_PD_SHIFT           6
#define LOWERPOWER_REG2_CAN_PD_MASK            0x00000040 //RW, 1 bit
#define LOWERPOWER_REG2_ROM_LS_SHIFT           7
#define LOWERPOWER_REG2_ROM_LS_MASK            0x00000080 //RW, 1 bit
#define LOWERPOWER_REG2_KEYEXP_PD_SHIFT        8
#define LOWERPOWER_REG2_KEYEXP_PD_MASK         0x00000100 //RW, 1 bit

#endif