#ifndef __ZN_SYSTEM_TIMER_H__
#define __ZN_SYSTEM_TIMER_H__

#ifdef __cplusplus
extern "C" {
#endif
#include "base_addr.h"
#include "zn_soc.h"



#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG     (SYSTIMER_BASE_ADDR+0x0000)
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_0_SHIFT        0
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_0_MASK         0x00000001 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_1_SHIFT        1
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_1_MASK         0x00000002 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_2_SHIFT        2
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_2_MASK         0x00000004 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_3_SHIFT        3
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_3_MASK         0x00000008 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_4_SHIFT        4
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_4_MASK         0x00000010 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_5_SHIFT        5
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_5_MASK         0x00000020 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_6_SHIFT        6
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_6_MASK         0x00000040 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_7_SHIFT        7
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CMP_EN_7_MASK         0x00000080 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CLEAR_SHIFT           8
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_CLEAR_MASK            0x00000100 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_PAUSE_SHIFT           9
#define SYSTIMER_REG_SYSTIMER_CMP_CTRL_REG_PAUSE_MASK            0x00000200 //RW, 1 bit

#define SYSTIMER_REG_SYSTIMER_TIMER_REG        (SYSTIMER_BASE_ADDR+0x0004)
#define SYSTIMER_REG_SYSTIMER_TIMER_REG_SYSTIMER_TIMER_REG_SHIFT 0
#define SYSTIMER_REG_SYSTIMER_TIMER_REG_SYSTIMER_TIMER_REG_MASK  0x00000000 //RO, 32 bit

#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG     (SYSTIMER_BASE_ADDR+0x0008)
#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG_CAP_EN_0_SHIFT        0
#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG_CAP_EN_0_MASK         0x00000001 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG_CAP_EN_1_SHIFT        1
#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG_CAP_EN_1_MASK         0x00000002 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG_CAP_EN_2_SHIFT        2
#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG_CAP_EN_2_MASK         0x00000004 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG_CAP_EN_3_SHIFT        3
#define SYSTIMER_REG_SYSTIMER_CAP_CTRL_REG_CAP_EN_3_MASK         0x00000008 //RW, 1 bit

#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG     (SYSTIMER_BASE_ADDR+0x000c)
#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG_CAP_EDGE_0_SHIFT      0
#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG_CAP_EDGE_0_MASK       0x00000003 //RW, 2 bit
#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG_CAP_EDGE_1_SHIFT      2
#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG_CAP_EDGE_1_MASK       0x0000000c //RW, 2 bit
#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG_CAP_EDGE_2_SHIFT      4
#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG_CAP_EDGE_2_MASK       0x00000030 //RW, 2 bit
#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG_CAP_EDGE_3_SHIFT      6
#define SYSTIMER_REG_SYSTIMER_CAP_EDGE_REG_CAP_EDGE_3_MASK       0x000000c0 //RW, 2 bit

#define SYSTIMER_REG_SYSTIMER_CMP_VALUE_REG(id)  (SYSTIMER_BASE_ADDR+0x00010+(id<<2))
#define SYSTIMER_REG_SYSTIMER_CMP_VALUE_REG_CMP_VAL_0_SHIFT    0
#define SYSTIMER_REG_SYSTIMER_CMP_VALUE_REG_CMP_VAL_0_MASK     0x00000000 //RW, 32 bit




#define SYSTIMER_REG_SYSTIMER_CAP_VALUE_REG(id)   (SYSTIMER_BASE_ADDR+0x0030+(id<<2))
#define SYSTIMER_REG_SYSTIMER_CAP_VALUE_REG_CAP_VAL_0_SHIFT    0
#define SYSTIMER_REG_SYSTIMER_CAP_VALUE_REG_CAP_VAL_0_MASK     0x00000000 //RO, 32 bit




#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG (SYSTIMER_BASE_ADDR+0x0040)
#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG_GPIO_SEL_0_SHIFT  0
#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG_GPIO_SEL_0_MASK   0x0000001f //RW, 5 bit
#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG_GPIO_SEL_1_SHIFT  8
#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG_GPIO_SEL_1_MASK   0x00001f00 //RW, 5 bit
#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG_GPIO_SEL_2_SHIFT  16
#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG_GPIO_SEL_2_MASK   0x001f0000 //RW, 5 bit
#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG_GPIO_SEL_3_SHIFT  24
#define SYSTIMER_REG_SYSTIMER_CAP_GPIO_SEL_REG_GPIO_SEL_3_MASK   0x1f000000 //RW, 5 bit


#define SYSTIMER_REG_SYSTIMER_INT_RAW          (SYSTIMER_BASE_ADDR+0x0044)
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CMP_IRQ_0_RAW_SHIFT        0
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CMP_IRQ_1_RAW_SHIFT        1
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CMP_IRQ_2_RAW_SHIFT        2
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CMP_IRQ_3_RAW_SHIFT        3
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CMP_IRQ_4_RAW_SHIFT        4
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CMP_IRQ_5_RAW_SHIFT        5
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CMP_IRQ_6_RAW_SHIFT        6
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CMP_IRQ_7_RAW_SHIFT        7
#define SYSTIMER_REG_SYSTIMER_INT_RAW_OVF_IRQ_RAW_SHIFT          8
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CAP_IRQ_0_RAW_SHIFT        9
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CAP_IRQ_1_RAW_SHIFT        10
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CAP_IRQ_2_RAW_SHIFT        11
#define SYSTIMER_REG_SYSTIMER_INT_RAW_CAP_IRQ_3_RAW_SHIFT        12


#define SYSTIMER_REG_SYSTIMER_INT_FORCE        (SYSTIMER_BASE_ADDR+0x0048)
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CMP_IRQ_0_RAW_SHIFT      0
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CMP_IRQ_1_RAW_SHIFT      1
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CMP_IRQ_2_RAW_SHIFT      2
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CMP_IRQ_3_RAW_SHIFT      3
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CMP_IRQ_4_RAW_SHIFT      4
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CMP_IRQ_5_RAW_SHIFT      5
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CMP_IRQ_6_RAW_SHIFT      6
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CMP_IRQ_7_RAW_SHIFT      7
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_OVF_IRQ_RAW_SHIFT        8
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CAP_IRQ_0_RAW_SHIFT      9
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CAP_IRQ_1_RAW_SHIFT      10
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CAP_IRQ_2_RAW_SHIFT      11
#define SYSTIMER_REG_SYSTIMER_INT_FORCE_CAP_IRQ_3_RAW_SHIFT      12


#define SYSTIMER_REG_SYSTIMER_INT_MASK         (SYSTIMER_BASE_ADDR+0x004c)
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_0_MASK_SHIFT      0
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_0_MASK_MASK       0x00000001 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_1_MASK_SHIFT      1
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_1_MASK_MASK       0x00000002 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_2_MASK_SHIFT      2
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_2_MASK_MASK       0x00000004 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_3_MASK_SHIFT      3
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_3_MASK_MASK       0x00000008 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_4_MASK_SHIFT      4
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_4_MASK_MASK       0x00000010 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_5_MASK_SHIFT      5
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_5_MASK_MASK       0x00000020 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_6_MASK_SHIFT      6
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_6_MASK_MASK       0x00000040 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_7_MASK_SHIFT      7
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CMP_IRQ_7_MASK_MASK       0x00000080 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_OVF_IRQ_MASK_SHIFT        8
#define SYSTIMER_REG_SYSTIMER_INT_MASK_OVF_IRQ_MASK_MASK         0x00000100 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CAP_IRQ_0_MASK_SHIFT      9
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CAP_IRQ_0_MASK_MASK       0x00000200 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CAP_IRQ_1_MASK_SHIFT      10
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CAP_IRQ_1_MASK_MASK       0x00000400 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CAP_IRQ_2_MASK_SHIFT      11
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CAP_IRQ_2_MASK_MASK       0x00000800 //RW, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CAP_IRQ_3_MASK_SHIFT      12
#define SYSTIMER_REG_SYSTIMER_INT_MASK_CAP_IRQ_3_MASK_MASK       0x00001000 //RW, 1 bit

#define SYSTIMER_REG_SYSTIMER_INT_STATUS       (SYSTIMER_BASE_ADDR+0x0050)
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_0_STATUS_SHIFT  0
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_0_STATUS_MASK   0x00000001 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_1_STATUS_SHIFT  1
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_1_STATUS_MASK   0x00000002 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_2_STATUS_SHIFT  2
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_2_STATUS_MASK   0x00000004 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_3_STATUS_SHIFT  3
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_3_STATUS_MASK   0x00000008 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_4_STATUS_SHIFT  4
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_4_STATUS_MASK   0x00000010 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_5_STATUS_SHIFT  5
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_5_STATUS_MASK   0x00000020 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_6_STATUS_SHIFT  6
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_6_STATUS_MASK   0x00000040 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_7_STATUS_SHIFT  7
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CMP_IRQ_7_STATUS_MASK   0x00000080 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_OVF_IRQ_STATUS_SHIFT    8
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_OVF_IRQ_STATUS_MASK     0x00000100 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CAP_IRQ_0_STATUS_SHIFT  9
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CAP_IRQ_0_STATUS_MASK   0x00000200 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CAP_IRQ_1_STATUS_SHIFT  10
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CAP_IRQ_1_STATUS_MASK   0x00000400 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CAP_IRQ_2_STATUS_SHIFT  11
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CAP_IRQ_2_STATUS_MASK   0x00000800 //RO, 1 bit
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CAP_IRQ_3_STATUS_SHIFT  12
#define SYSTIMER_REG_SYSTIMER_INT_STATUS_CAP_IRQ_3_STATUS_MASK   0x00001000 //RO, 1 bit







#define CMP_CHANNEL_NUM            (8)
#define CAP_CHANNEL_NUM            (4)


#define  ENABLE     1
#define  DISABLE    0

typedef enum
{
    CAP_GPIO_RISE_EDGE=0,
    CAP_GPIO_FALL_EDGE,
    CAP_GPIO_BOTH_EDGE
}SYSTIMER_CapGpioEdgeType;


typedef struct
{
    uint8_t capId;        /* capId ID, is 0,1,2,3*/
    SYSTIMER_CapGpioEdgeType capMode;
    uint8_t gpio_pin;
    uint8_t interruptEn;
} SYSTIMER_CfgCapType;


typedef struct
{
    uint8_t cmpId;        /* cmpId ID, is 0,1,2,3,4,5,6,7*/
    uint32_t cmpval;  
    uint8_t interruptEn;
} SYSTIMER_CfgCmpType;

typedef void (*SysTimerCallback)(uint32_t arg); 



uint32_t systimer_get_cur_val(void);
int32_t systimer_cmp_channel_ctrl(uint32_t channel_id,uint8_t status);
void systimer_timer_clear(uint8_t en);
void systimer_timer_pause(uint8_t en);
void systimer_timer_run(void);
int32_t systimer_cap_channel_ctrl(uint32_t channel_id,uint8_t status);
int32_t systimer_cap_set_edge_mode(uint32_t channel_id,SYSTIMER_CapGpioEdgeType mode);
int32_t systimer_cap_get_edge_mode(uint32_t channel_id,SYSTIMER_CapGpioEdgeType *mode);
int32_t systimer_cmp_set_compare_value(uint32_t channel_id,uint32_t value);
int32_t systimer_cmp_get_compare_value(uint32_t *value);
int32_t systimer_cap_set_gpio_sel(uint32_t channel_id,uint8_t gpio_pin);
int32_t systimer_cap_get_gpio_sel(uint32_t channel_id,uint8_t *gpio_pin);
int32_t systimer_get_cap_val(uint8_t channel_id, uint32_t *capval);
int32_t systimer_cap_set_irq_enable(uint32_t channel_id);
int32_t systimer_cap_set_irq_disable(uint32_t channel_id);
int32_t systimer_ovf_set_irq_enable(void);
int32_t systimer_ovf_set_irq_disable(void);
int32_t systimer_cmp_set_irq_enable(uint32_t channel_id);
int32_t systimer_cmp_set_irq_disable(uint32_t channel_id);
void systimer_clear_irq_status(void);
uint32_t systimer_get_irq_status(void);
void systimer_set_callback(SysTimerCallback callback);
void systimer_cap_init(SYSTIMER_CfgCapType *capConfig);
void systimer_cmp_init(SYSTIMER_CfgCmpType *cmpConfig);

#ifdef __cplusplus
}
#endif


#endif
